/**
 * DEMO / DEVELOPMENT SEED DATA ONLY.
 * No real student data. Run with: npm run db:seed --workspace apps/api
 */
import argon2 from "argon2";
import { connectDB, disconnectDB } from "./config/db.js";
import { User } from "./models/User.js";
import { LearningModule } from "./models/LearningModule.js";
import { Lesson } from "./models/Lesson.js";
import { Quiz } from "./models/Quiz.js";
import { Question } from "./models/Question.js";
import { QuizAttempt } from "./models/QuizAttempt.js";
import { ModuleProgress } from "./models/ModuleProgress.js";
import { AwarenessAssessment } from "./models/AwarenessAssessment.js";

const MODULES = [
  {
    slug: "password-fundamentals",
    title: "What Makes a Password Strong?",
    category: "Passwords",
    description: "Understand the core properties — length, unpredictability, and uniqueness — that make a password hard to guess or crack.",
    objectives: ["Explain why length beats complexity", "Identify predictable patterns", "Estimate password entropy conceptually"],
    lessons: [
      ["Length vs. Complexity", "A 16-character passphrase like 'correct-horse-battery-staple' is far harder to crack than 'P@ss1!' because guessing difficulty grows exponentially with length. Composition rules (forcing symbols) often push people toward predictable substitutions like 'P@ssw0rd', which attackers already expect."],
      ["Entropy, Simply Explained", "Entropy measures unpredictability, in bits. Each added random character roughly doubles the number of guesses an attacker needs. Dictionary words, names, and dates carry very little entropy even when combined."],
      ["Predictable Patterns", "Keyboard walks (qwerty, 12345), repeated characters (aaaa), and sequences (abcd) are among the first patterns automated tools try. Avoiding them removes your password from the 'easy' bucket immediately."],
      ["Personal Information Is Guessable", "Names, birthdays, pet names, and course codes are often discoverable from social media and are commonly tried in targeted guessing attempts."],
      ["Building a Strong Passphrase", "Combine 4–6 unrelated words, or a memorable but non-obvious sentence, and add a personal twist that isn't guessable from public information."],
    ],
  },
  {
    slug: "password-reuse-and-managers",
    title: "Password Reuse and Password Managers",
    category: "Passwords",
    description: "Learn why reusing passwords across sites is one of the biggest risks students face, and how password managers solve it.",
    objectives: ["Explain credential stuffing", "Evaluate password manager benefits", "Adopt a unique-password habit"],
    lessons: [
      ["Why Reuse Is Dangerous", "If one site you use is breached, attackers try the same email/password pair on many other sites — this is called credential stuffing. Reuse turns one breach into many compromised accounts."],
      ["How Password Managers Help", "A password manager generates and stores a long, unique password per site, so you only need to remember one strong master password."],
      ["Choosing a Password Manager", "Look for strong encryption, open security audits, and cross-device sync. Built-in browser managers are a reasonable starting point for students."],
      ["Master Password Hygiene", "Your master password should be the strongest, most memorable passphrase you own — it protects everything else."],
      ["Recovering Access Safely", "Set up account recovery options (backup codes, recovery email) for your password manager before you need them."],
    ],
  },
  {
    slug: "multi-factor-authentication",
    title: "Multi-Factor Authentication",
    category: "Authentication",
    description: "Discover how a second verification step protects your account even if your password is exposed.",
    objectives: ["Define MFA and its factors", "Compare MFA methods", "Enable MFA on a student account"],
    lessons: [
      ["What Is MFA?", "Multi-factor authentication requires two or more proofs of identity: something you know (password), something you have (phone/app), or something you are (fingerprint)."],
      ["Authenticator Apps vs SMS", "Authenticator apps generate time-based codes offline and resist SIM-swap attacks better than SMS codes, though SMS is still better than no MFA at all."],
      ["One-Time Passwords (OTPs)", "OTPs are single-use codes valid for a short window, commonly generated by an authenticator app or sent via SMS/email."],
      ["What Happens If You Lose Your Device", "Save backup codes somewhere safe and separate from your phone when you enable MFA, so you aren't locked out."],
      ["Enabling MFA on Common Platforms", "Most email, banking, and learning platforms offer MFA under Security Settings — enabling it is one of the highest-impact security actions a student can take."],
    ],
  },
  {
    slug: "authentication-vs-authorization",
    title: "Authentication vs. Authorization",
    category: "Authentication",
    description: "Clarify the difference between proving who you are and what you're allowed to do.",
    objectives: ["Distinguish authentication from authorization", "Recognize access-control failures"],
    lessons: [
      ["Authentication: Proving Identity", "Authentication answers 'who are you?' — typically via password, biometrics, or a token."],
      ["Authorization: Granting Access", "Authorization answers 'what are you allowed to do?' — for example, a student cannot access admin-only pages even after logging in."],
      ["Why the Distinction Matters", "A system can authenticate you correctly but still fail if it authorizes you for more than it should — this is a common source of data leaks."],
      ["Role-Based Access Control", "Assigning permissions by role (student, admin) rather than per-person keeps systems predictable and auditable."],
      ["Everyday Examples", "Logging into a student portal is authentication; being blocked from another student's grades is authorization."],
    ],
  },
  {
    slug: "phishing-and-social-engineering",
    title: "Phishing and Social Engineering",
    category: "Threats",
    description: "Recognize manipulation tactics used to trick people into revealing credentials or sensitive data.",
    objectives: ["Identify phishing indicators", "Respond safely to suspicious requests"],
    lessons: [
      ["What Is Phishing?", "Phishing uses fake emails, messages, or websites that impersonate a trusted source to trick you into entering credentials."],
      ["Common Red Flags", "Urgency, unexpected attachments, mismatched sender domains, and links requesting a password are classic phishing signals."],
      ["Social Engineering Tactics", "Attackers exploit trust, authority, and urgency — for example, impersonating IT support to request your password 'for verification'."],
      ["Verifying Through Official Channels", "If a message asks for credentials, contact the organization directly using a known number or website instead of replying or clicking."],
      ["What to Do If You Clicked", "Change your password immediately from a trusted device, enable MFA, and report the incident to your institution's IT team."],
    ],
  },
  {
    slug: "credential-stuffing-and-account-takeover",
    title: "Credential Stuffing and Account Takeover",
    category: "Threats",
    description: "Understand how leaked credentials are automated into large-scale account takeover attempts.",
    objectives: ["Explain credential stuffing mechanics", "List account-takeover warning signs"],
    lessons: [
      ["How Credential Stuffing Works", "Attackers use lists of breached email/password pairs and automated tools to try them across many sites at once."],
      ["Why Rate Limiting Helps", "Limiting login attempts per account slows automated guessing dramatically without inconveniencing real users."],
      ["Signs of Account Takeover", "Unexpected password reset emails, login alerts from unfamiliar locations, or being logged out unexpectedly can indicate compromise."],
      ["Immediate Response Steps", "Change your password, sign out of all sessions, enable MFA, and check for unfamiliar account changes."],
      ["Checking If You've Been Breached", "Reputable breach-notification services let you check if an email address appeared in a known breach, without needing your password."],
    ],
  },
  {
    slug: "secure-recovery-and-shared-devices",
    title: "Secure Password Recovery and Shared Computers",
    category: "Practices",
    description: "Protect your accounts during recovery flows and when using shared or public devices.",
    objectives: ["Configure safe recovery options", "Practice safe use of shared computers"],
    lessons: [
      ["Setting Up Recovery Safely", "Use a recovery email and phone number you control, and keep them up to date so legitimate resets work smoothly."],
      ["Recognizing Fake Reset Emails", "Genuine reset links go to the site's real domain and are never accompanied by a request to 'confirm' your password over email."],
      ["Using Public or Shared Computers", "Always log out fully and use private/incognito mode on shared or lab computers — never select 'remember me'."],
      ["Clearing Sessions After Use", "Check for and revoke active sessions on shared devices from your account's security settings when possible."],
      ["Campus Wi-Fi Considerations", "Prefer HTTPS sites and avoid entering credentials on unfamiliar networks without a VPN where feasible."],
    ],
  },
  {
    slug: "everyday-secure-browsing",
    title: "Secure Browsing and Protecting Student Accounts",
    category: "Practices",
    description: "Build daily habits that reduce your overall exposure to account compromise.",
    objectives: ["Identify secure connection indicators", "Apply daily account-hygiene habits"],
    lessons: [
      ["Reading URLs Before You Click", "Check the domain carefully — attackers use lookalike domains such as 'polyteknic-login.com' to imitate real institutions."],
      ["HTTPS and Site Trust", "A padlock icon means the connection is encrypted, but does not guarantee the site itself is legitimate — verify the domain too."],
      ["Keeping Software Updated", "Browser and OS updates frequently patch security flaws that attackers actively exploit."],
      ["Reviewing App Permissions", "Periodically review which third-party apps have access to your student or email account and remove ones you no longer use."],
      ["Building a Personal Security Routine", "Combine unique passwords, a password manager, MFA, and periodic account reviews into a five-minute monthly habit."],
    ],
  },
];

const QUESTIONS: {
  moduleSlug: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  topic: string;
}[] = [
  { moduleSlug: "password-fundamentals", prompt: "Which factor most increases a password's resistance to guessing?", options: ["Adding one extra symbol", "Increasing overall length", "Using your birth year", "Using a common word"], correctIndex: 1, explanation: "Length increases the number of possible combinations exponentially, making it the strongest lever against guessing.", topic: "Password Strength" },
  { moduleSlug: "password-fundamentals", prompt: "'Qwerty12345' is weak mainly because it contains:", options: ["A keyboard pattern", "Too many numbers", "Too much length", "Special characters"], correctIndex: 0, explanation: "Keyboard walks like 'qwerty' are among the first patterns automated cracking tools try.", topic: "Password Strength" },
  { moduleSlug: "password-reuse-and-managers", prompt: "What is the main risk of reusing the same password across multiple sites?", options: ["It's harder to type", "One breach can compromise many accounts", "It uses more memory", "Sites will reject it"], correctIndex: 1, explanation: "Credential stuffing attacks try leaked email/password pairs across many other sites, so reuse multiplies the damage of a single breach.", topic: "Password Reuse" },
  { moduleSlug: "multi-factor-authentication", prompt: "Which best describes multi-factor authentication?", options: ["Using two different passwords", "Combining two or more independent proofs of identity", "Changing your password twice a year", "Logging in from two devices"], correctIndex: 1, explanation: "MFA combines independent factors — something you know, have, or are — so a stolen password alone isn't enough to log in.", topic: "Authentication" },
  { moduleSlug: "authentication-vs-authorization", prompt: "After logging in successfully, a student tries to open an admin-only page and is blocked. This is an example of:", options: ["Authentication failure", "Authorization working correctly", "A password reset", "A phishing attempt"], correctIndex: 1, explanation: "Authentication confirmed who the user is; authorization then correctly denied access based on their role.", topic: "Authentication vs Authorization" },
  { moduleSlug: "phishing-and-social-engineering", prompt: "You receive a message asking you to click a link and enter your student account password immediately. What should you do?", options: ["Click immediately", "Reply with your password", "Verify the request through an official channel", "Forward your password to a friend"], correctIndex: 2, explanation: "Legitimate organizations don't ask you to send passwords via email or urgent links. Always verify through a known, official channel.", topic: "Phishing" },
  { moduleSlug: "phishing-and-social-engineering", prompt: "Which is the strongest phishing warning sign?", options: ["A message with a company logo", "A request for urgent action plus a credential request", "An email sent during business hours", "A message with no attachments"], correctIndex: 1, explanation: "Urgency combined with a request for credentials is a classic manipulation pattern used to bypass careful thinking.", topic: "Phishing" },
  { moduleSlug: "credential-stuffing-and-account-takeover", prompt: "What is credential stuffing?", options: ["Guessing passwords one character at a time", "Automated reuse of leaked email/password pairs across many sites", "Encrypting a password twice", "A type of phishing email"], correctIndex: 1, explanation: "Attackers automate testing of breached credential pairs against many other services, hoping users reused the same password.", topic: "Account Security" },
  { moduleSlug: "secure-recovery-and-shared-devices", prompt: "On a shared lab computer, what should you always do after using your student account?", options: ["Select 'remember me'", "Leave the tab open for next time", "Log out fully and close the session", "Bookmark your password"], correctIndex: 2, explanation: "Fully logging out prevents the next user of a shared computer from accessing your account.", topic: "Shared Devices" },
  { moduleSlug: "everyday-secure-browsing", prompt: "A login page's URL is 'polyteknic-login.com' instead of your institution's real domain. This is most likely:", options: ["A normal mirror site", "A lookalike phishing domain", "A caching server", "A secure backup login"], correctIndex: 1, explanation: "Attackers register lookalike domains that closely resemble real institutional URLs to trick users into entering credentials.", topic: "Secure Browsing" },
];

async function main() {
  await connectDB();
  console.log("Seeding DEMO data — not for production use...");

  // Wipe existing demo/content data so this script is safely re-runnable.
  await Promise.all([
    Question.deleteMany({}),
    Quiz.deleteMany({}),
    Lesson.deleteMany({}),
    LearningModule.deleteMany({}),
    ModuleProgress.deleteMany({}),
    QuizAttempt.deleteMany({}),
    AwarenessAssessment.deleteMany({}),
  ]);

  const adminPasswordHash = await argon2.hash("Admin-Demo-2026!", { type: argon2.argon2id });
  const studentPasswordHash = await argon2.hash("Student-Demo-2026!", { type: argon2.argon2id });

  await User.findOneAndUpdate(
    { email: "admin@localhost.test" },
    { email: "admin@localhost.test", passwordHash: adminPasswordHash, role: "ADMIN" },
    { upsert: true }
  );

  let student = await User.findOne({ email: "student@localhost.test" });
  if (!student) {
    student = await User.create({
      email: "student@localhost.test",
      passwordHash: studentPasswordHash,
      role: "STUDENT",
      profile: {
        fullName: "Demo Student (Seed Data)",
        studentId: "DEMO-0001",
        department: "Computer Science",
        polytechnic: "Demo Polytechnic",
        level: "ND2",
      },
    });
  }

  const moduleIdBySlug = new Map<string, string>();

  for (const [index, m] of MODULES.entries()) {
    const module = await LearningModule.create({
      slug: m.slug,
      title: m.title,
      description: m.description,
      category: m.category,
      difficulty: "BEGINNER",
      objectives: m.objectives,
      durationMin: 20,
      order: index,
      isPublished: true,
    });
    moduleIdBySlug.set(m.slug, module.id);

    await Lesson.insertMany(
      m.lessons.map(([title, content], i) => ({
        moduleId: module._id,
        title,
        content,
        keyTakeaways: [content.split(".")[0] + "."],
        order: i,
      }))
    );
  }

  const questionsBySlug = new Map<string, typeof QUESTIONS>();
  for (const q of QUESTIONS) {
    const list = questionsBySlug.get(q.moduleSlug) ?? [];
    list.push(q);
    questionsBySlug.set(q.moduleSlug, list);
  }

  for (const [slug, questions] of questionsBySlug.entries()) {
    const moduleId = moduleIdBySlug.get(slug);
    if (!moduleId) continue;

    const quiz = await Quiz.create({
      moduleId,
      title: `Knowledge Check: ${MODULES.find((m) => m.slug === slug)?.title}`,
      description: "Seed/demo quiz",
      isPublished: true,
    });

    const createdQuestions = await Question.insertMany(
      questions.map((q, i) => ({
        quizId: quiz._id,
        type: "MULTIPLE_CHOICE",
        prompt: q.prompt,
        options: q.options,
        correctIndex: q.correctIndex,
        explanation: q.explanation,
        topic: q.topic,
        difficulty: "BEGINNER",
        order: i,
      }))
    );

    if (slug === "password-fundamentals" || slug === "phishing-and-social-engineering") {
      await QuizAttempt.create({
        userId: student._id,
        quizId: quiz._id,
        score: 100,
        totalQuestions: createdQuestions.length,
        completedAt: new Date(),
        answers: createdQuestions.map((q) => ({
          questionId: q._id,
          selectedIndex: q.correctIndex,
          isCorrect: true,
          question: { prompt: q.prompt, explanation: q.explanation, correctIndex: q.correctIndex, options: q.options },
        })),
      });
      await ModuleProgress.findOneAndUpdate(
        { userId: student._id, moduleId },
        { userId: student._id, moduleId, percentComplete: 100, isCompleted: true },
        { upsert: true }
      );
    }
  }

  await AwarenessAssessment.create({
    userId: student._id,
    type: "PRE_TEST",
    scorePercent: 54,
    responses: [
      { topic: "Passwords", isCorrect: true },
      { topic: "Phishing", isCorrect: false },
      { topic: "MFA", isCorrect: false },
    ],
  });
  await AwarenessAssessment.create({
    userId: student._id,
    type: "POST_TEST",
    scorePercent: 81,
    responses: [
      { topic: "Passwords", isCorrect: true },
      { topic: "Phishing", isCorrect: true },
      { topic: "MFA", isCorrect: true },
    ],
  });

  console.log("Seed complete.");
  console.log("Demo admin login:   admin@localhost.test / Admin-Demo-2026!");
  console.log("Demo student login: student@localhost.test / Student-Demo-2026!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await disconnectDB();
  });
